# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-26 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhmProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guess',
            new_name='Guest',
        ),
    ]
